export {default as Navbar} from './Navbar/Navbar.js';
export {default as Landing} from './Landing/Landing.js';
export {default as About} from './About/About.js';
export {default as Mywork} from './My_Work/Mywork.js';
export {default as Testimonial} from './Testimonials/Testimonial.js'
export {default as LogedUser} from './LogerUser/LogedUser.js'
export {default as Skills} from './Skills/Skills.js'
export {default as Resume} from './Resume/Resume.js'
export {default as UserAdmin} from './UserAdmin/UserAdmin.js'
export {default as Contact} from './Contact/Contact.js'